version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      MONGODB_URI: mongodb://mongo:27017
      JWT_SECRET: e9896fc41cd64cfd44b359f5b4cdf2a5897e94ee9a8644c3cebc52270486e93a852f8ca029c67a6c7ee22219b9fb4c057c7c13f7cb8ed104f7f140effd7341a0
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    depends_on:
      - mongo

volumes:
  mongo-data: